name: Deploy

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches:
      - master
      - main
#  watch:
#    types: [started]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          # “最近更新时间“ 等 Git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
          persist-credentials: false

      - name: Install and Build
        env:
          TZ: Asia/Shanghai
        run: |
          export GOOGLE_GA=${{ secrets.GOOGLE_GA }} GOOGLE_SEARCH_CONSOLE=${{ secrets.GOOGLE_SEARCH_CONSOLE }}
          git --no-pager log --oneline -n 20
          npm install
          npm run docs:build

      - name: Deploy Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.docs }}
          publish_dir: docs/.vuepress/dist
          commit_message: ${{ github.event.head_commit.message }}
          cname: yuedu.juhua.fun

